using System.Text;
using System.Text.Json;
using AIAnalysisService.Models;
using static System.Net.Mime.MediaTypeNames;

namespace AIAnalysisService.Services
{
    public class GeminiService : IGeminiService
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IConfiguration _configuration;
        private readonly ILogger<GeminiService> _logger;
        private readonly HttpClient _client;

        public GeminiService(
            IHttpClientFactory httpClientFactory,
            IConfiguration configuration,
            ILogger<GeminiService> logger,
            HttpClient client)
        {
            _httpClientFactory = httpClientFactory;
            _configuration = configuration;
            _logger = logger;
            _client = client;
        }

        public async Task<AnalysisResponse> AnalyzeStockAsync(AnalysisRequest request)
        {
            try
            {
                var apiKey = _configuration["Gemini:ApiKey"];
                var baseUrl = _configuration["Gemini:BaseUrl"];
                var model = _configuration["Gemini:Model"];

                if (string.IsNullOrEmpty(apiKey))
                {
                    throw new InvalidOperationException("Gemini API key is not configured");
                }

                // Build the prompt with stock data
                var fullPrompt = BuildPromptWithStockData(request);

                // Create Gemini API request
                var geminiRequest = new GeminiRequest
                {
                    Contents = new List<Content>
                    {
                        new Content
                        {
                            Parts = new List<Part>
                            {
                                new Part { Text = fullPrompt }
                            }
                        }
                    }
                };

                var client = _httpClientFactory.CreateClient();
                var url = $"{baseUrl}/{model}:generateContent?key={apiKey}";

                var jsonContent = JsonSerializer.Serialize(geminiRequest);
                var httpContent = new StringContent(jsonContent, Encoding.UTF8, "application/json");

                _logger.LogInformation("Sending request to Gemini API for symbol: {Symbol}", request.Symbol);

                var response = await client.PostAsync(url, httpContent);
                var responseContent = await response.Content.ReadAsStringAsync();

                if (!response.IsSuccessStatusCode)
                {
                    _logger.LogError("Gemini API error: {StatusCode} - {Content}", response.StatusCode, responseContent);
                    return new AnalysisResponse
                    {
                        Symbol = request.Symbol,
                        Success = false,
                        ErrorMessage = $"Gemini API error: {response.StatusCode}",
                        Timestamp = DateTime.UtcNow
                    };
                }

                var geminiResponse = JsonSerializer.Deserialize<GeminiResponse>(responseContent);

                if (geminiResponse?.Candidates == null || geminiResponse.Candidates.Count == 0)
                {
                    _logger.LogError("No candidates in Gemini response");
                    return new AnalysisResponse
                    {
                        Symbol = request.Symbol,
                        Success = false,
                        ErrorMessage = "No analysis generated by Gemini",
                        Timestamp = DateTime.UtcNow
                    };
                }

                var analysisText = geminiResponse.Candidates[0]?.Content?.Parts?[0]?.Text ?? "No analysis available";

                _logger.LogInformation("Successfully received analysis from Gemini for symbol: {Symbol}", request.Symbol);

                return new AnalysisResponse
                {
                    Symbol = request.Symbol,
                    Analysis = analysisText,
                    Success = true,
                    Timestamp = DateTime.UtcNow
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error analyzing stock with Gemini for symbol: {Symbol}", request.Symbol);
                return new AnalysisResponse
                {
                    Symbol = request.Symbol,
                    Success = false,
                    ErrorMessage = ex.Message,
                    Timestamp = DateTime.UtcNow
                };
            }
        }

        public async Task<string> AnalyzeImage(string prompt, List<ImageInput> images)
        {
            if (images == null || images.Count == 0)
                throw new ArgumentException("At least one image is required");

            if (images.Count > 5)
                throw new ArgumentException("Maximum 5 images are supported");

            var apiKey = _configuration["Gemini:ApiKey"];
            var baseUrl = _configuration["Gemini:BaseUrl"];
            var model = _configuration["Gemini:Model"];
            var url = $"{baseUrl}/{model}:generateContent?key={apiKey}";

            var parts = new List<object>();

            // Start med hovedprompt
            parts.Add(new
            {
                text = prompt
            });

            // Tilf�j hvert billede som separat part
            foreach (var image in images)
            {
                if (!string.IsNullOrWhiteSpace(image.Description))
                {
                    parts.Add(new
                    {
                        text = $"Image context: {image.Description}"
                    });
                }

                parts.Add(new
                {
                    inline_data = new
                    {
                        mime_type = image.MimeType,
                        data = image.Base64
                    }
                });
            }


            var payload = new
            {
                contents = new[]
                {
                    new
                    {
                        parts = parts
                    }
                }
            };

            var json = JsonSerializer.Serialize(payload);
            var res = await _client.PostAsync(url,
                new StringContent(json, Encoding.UTF8, "application/json"));

            var body = await res.Content.ReadAsStringAsync();
            if (!res.IsSuccessStatusCode)
            {
                _logger.LogError("Gemini image analysis failed: {Status} - {Body}", res.StatusCode, body);
                return $"Gemini failed: {res.StatusCode} - {body}";
            }


            var response = JsonDocument.Parse(body);

            var text = response
              .RootElement
              .GetProperty("candidates")[0]
              .GetProperty("content")
              .GetProperty("parts")[0]
              .GetProperty("text")
              .GetString();

            return text ?? "No analysis returned";
        }

        private string BuildPromptWithStockData(AnalysisRequest request)
        {
            var sb = new StringBuilder();

            sb.AppendLine($"{request.Prompt}");
            sb.AppendLine();
            sb.AppendLine($"Til teknisk analyse for: {request.Symbol}, anvend de nedenstående tekniske indikatorer.");
            sb.AppendLine();

            if (request.StockData != null)
            {
                sb.AppendLine("Nuværende Stock Data:");
                sb.AppendLine($"- Symbol: {request.StockData.Symbol}");
                sb.AppendLine($"- Nuværende Price: ${request.StockData.CurrentPrice:F2}");
                sb.AppendLine($"- Dato: {request.StockData.Date:yyyy-MM-dd}");
                sb.AppendLine();

                var indicators = request.StockData.Indicators;
                sb.AppendLine("Technical Indicators:");
                sb.AppendLine();

                sb.AppendLine("Moving Averages:");
                sb.AppendLine($"- SMA 20-day: ${indicators.SMA_20:F2}");
                sb.AppendLine($"- SMA 50-day: ${indicators.SMA_50:F2}");
                sb.AppendLine($"- SMA 200-day: ${indicators.SMA_200:F2}");
                sb.AppendLine($"- EMA 12-day: ${indicators.EMA_12:F2}");
                sb.AppendLine($"- EMA 26-day: ${indicators.EMA_26:F2}");
                sb.AppendLine();

                sb.AppendLine("Momentum Indicators:");
                sb.AppendLine($"- RSI (14-day): {indicators.RSI_14:F2}");
                sb.AppendLine($"- RSI Trend: {indicators.RSITrend:F2}");
                sb.AppendLine($"- MACD Line: {indicators.MACD_Line:F2}");
                sb.AppendLine($"- MACD Signal: {indicators.MACD_Signal:F2}");
                sb.AppendLine($"- MACD Histogram: {indicators.MACD_Histogram:F2}");
                sb.AppendLine($"- MACD State: {indicators.MACDState:F2}");
                sb.AppendLine();

                sb.AppendLine("Bollinger Bands:");
                sb.AppendLine($"- Upper Band: ${indicators.BollingerUpper:F2}");
                sb.AppendLine($"- Middle Band: ${indicators.BollingerMiddle:F2}");
                sb.AppendLine($"- Lower Band: ${indicators.BollingerLower:F2}");
                sb.AppendLine();

                sb.AppendLine("Volume Analysis:");
                sb.AppendLine($"- Average Volume (20-day): {indicators.AverageVolume_20:N0}");
                sb.AppendLine($"- Volume Change: {indicators.VolumeChangePercent:F2}%");
                sb.AppendLine();

                sb.AppendLine("Price Metrics:");
                sb.AppendLine($"- Day Change: {indicators.DayChangePercent:F2}%");
                sb.AppendLine($"- 52-Week High: ${indicators.Week52High:F2}");
                sb.AppendLine($"- 52-Week Low: ${indicators.Week52Low:F2}");
                sb.AppendLine($"- Price vs SMA 50: {indicators.PriceVsSMA50}");
                sb.AppendLine($"- Price vs SMA 200: {indicators.PriceVsSMA200}");

                sb.AppendLine("Volume-Based Momentum:");
                sb.AppendLine($"- On-Balance Volume (OBV): {indicators.OBV:N0}");
                sb.AppendLine($"- OBV Trend: {indicators.OBVTrend:F2}");
                sb.AppendLine();

                _logger.LogInformation($"DEBUG: Indicators");
                _logger.LogInformation($"SMA_20 = {indicators.SMA_20}");
                _logger.LogInformation($"SMA_200 = {indicators.SMA_50}");
                _logger.LogInformation($"SMA_50 = {indicators.SMA_200}");
                _logger.LogInformation($"EMA_12 = {indicators.EMA_12}");
                _logger.LogInformation($"EMA_26 = {indicators.EMA_26}");
                _logger.LogInformation($"RSI_14 = {indicators.RSI_14}");
                _logger.LogInformation($"MACD_Line = {indicators.MACD_Line}");
                _logger.LogInformation($"MACD_Signal = {indicators.MACD_Signal}");
                _logger.LogInformation($"MACD_Histogram = {indicators.MACD_Histogram}");
                _logger.LogInformation($"BollingerUpper = {indicators.BollingerUpper}");
                _logger.LogInformation($"BollingerMiddle = {indicators.BollingerMiddle}");
                _logger.LogInformation($"BollingerLower = {indicators.BollingerLower}");
                _logger.LogInformation($"AverageVolume_20 = {indicators.AverageVolume_20}");
                _logger.LogInformation($"VolumeChangePercent = {indicators.VolumeChangePercent}");

                _logger.LogInformation($"CurrentPrice = {indicators.CurrentPrice}");
                _logger.LogInformation($"DayChangePercent = {indicators.DayChangePercent}");
                _logger.LogInformation($"Week52High = {indicators.Week52High}");
                _logger.LogInformation($"Week52Low = {indicators.Week52Low}");
                _logger.LogInformation($"PriceVsSMA50 = {indicators.PriceVsSMA50}");
                _logger.LogInformation($"PriceVsSMA200 = {indicators.PriceVsSMA200}");
            }

            return sb.ToString();
        }
    }
}
