using System.Text;
using System.Text.Json;
using AIAnalysisService.Models;

namespace AIAnalysisService.Services
{
    public class GeminiService : IGeminiService
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IConfiguration _configuration;
        private readonly ILogger<GeminiService> _logger;

        public GeminiService(
            IHttpClientFactory httpClientFactory,
            IConfiguration configuration,
            ILogger<GeminiService> logger)
        {
            _httpClientFactory = httpClientFactory;
            _configuration = configuration;
            _logger = logger;
        }

        public async Task<AnalysisResponse> AnalyzeStockAsync(AnalysisRequest request)
        {
            try
            {
                var apiKey = _configuration["Gemini:ApiKey"];
                var baseUrl = _configuration["Gemini:BaseUrl"];
                var model = _configuration["Gemini:Model"];

                if (string.IsNullOrEmpty(apiKey))
                {
                    throw new InvalidOperationException("Gemini API key is not configured");
                }

                // Build the prompt with stock data
                var fullPrompt = BuildPromptWithStockData(request);

                // Create Gemini API request
                var geminiRequest = new GeminiRequest
                {
                    Contents = new List<Content>
                    {
                        new Content
                        {
                            Parts = new List<Part>
                            {
                                new Part { Text = fullPrompt }
                            }
                        }
                    }
                };

                var client = _httpClientFactory.CreateClient();
                var url = $"{baseUrl}/{model}:generateContent?key={apiKey}";

                var jsonContent = JsonSerializer.Serialize(geminiRequest);
                var httpContent = new StringContent(jsonContent, Encoding.UTF8, "application/json");

                _logger.LogInformation("Sending request to Gemini API for symbol: {Symbol}", request.Symbol);

                var response = await client.PostAsync(url, httpContent);
                var responseContent = await response.Content.ReadAsStringAsync();

                if (!response.IsSuccessStatusCode)
                {
                    _logger.LogError("Gemini API error: {StatusCode} - {Content}", response.StatusCode, responseContent);
                    return new AnalysisResponse
                    {
                        Symbol = request.Symbol,
                        Success = false,
                        ErrorMessage = $"Gemini API error: {response.StatusCode}",
                        Timestamp = DateTime.UtcNow
                    };
                }

                var geminiResponse = JsonSerializer.Deserialize<GeminiResponse>(responseContent);

                if (geminiResponse?.Candidates == null || geminiResponse.Candidates.Count == 0)
                {
                    _logger.LogError("No candidates in Gemini response");
                    return new AnalysisResponse
                    {
                        Symbol = request.Symbol,
                        Success = false,
                        ErrorMessage = "No analysis generated by Gemini",
                        Timestamp = DateTime.UtcNow
                    };
                }

                var analysisText = geminiResponse.Candidates[0]?.Content?.Parts?[0]?.Text ?? "No analysis available";

                _logger.LogInformation("Successfully received analysis from Gemini for symbol: {Symbol}", request.Symbol);

                return new AnalysisResponse
                {
                    Symbol = request.Symbol,
                    Analysis = analysisText,
                    Success = true,
                    Timestamp = DateTime.UtcNow
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error analyzing stock with Gemini for symbol: {Symbol}", request.Symbol);
                return new AnalysisResponse
                {
                    Symbol = request.Symbol,
                    Success = false,
                    ErrorMessage = ex.Message,
                    Timestamp = DateTime.UtcNow
                };
            }
        }

        private string BuildPromptWithStockData(AnalysisRequest request)
        {
            var sb = new StringBuilder();

            sb.AppendLine($"User Prompt: {request.Prompt}");
            sb.AppendLine();
            sb.AppendLine($"Stock Analysis Request for: {request.Symbol}");
            sb.AppendLine();

            if (request.StockData != null)
            {
                sb.AppendLine("Current Stock Data:");
                sb.AppendLine($"- Symbol: {request.StockData.Symbol}");
                sb.AppendLine($"- Current Price: ${request.StockData.CurrentPrice:F2}");
                sb.AppendLine($"- Date: {request.StockData.Date:yyyy-MM-dd}");
                sb.AppendLine();

                var indicators = request.StockData.Indicators;
                sb.AppendLine("Technical Indicators:");
                sb.AppendLine();

                sb.AppendLine("Moving Averages:");
                sb.AppendLine($"- SMA 20-day: ${indicators.SMA_20:F2}");
                sb.AppendLine($"- SMA 50-day: ${indicators.SMA_50:F2}");
                sb.AppendLine($"- SMA 200-day: ${indicators.SMA_200:F2}");
                sb.AppendLine($"- EMA 12-day: ${indicators.EMA_12:F2}");
                sb.AppendLine($"- EMA 26-day: ${indicators.EMA_26:F2}");
                sb.AppendLine();

                sb.AppendLine("Momentum Indicators:");
                sb.AppendLine($"- RSI (14-day): {indicators.RSI_14:F2}");
                sb.AppendLine($"- MACD Line: {indicators.MACD_Line:F2}");
                sb.AppendLine($"- MACD Signal: {indicators.MACD_Signal:F2}");
                sb.AppendLine($"- MACD Histogram: {indicators.MACD_Histogram:F2}");
                sb.AppendLine();

                sb.AppendLine("Bollinger Bands:");
                sb.AppendLine($"- Upper Band: ${indicators.BollingerUpper:F2}");
                sb.AppendLine($"- Middle Band: ${indicators.BollingerMiddle:F2}");
                sb.AppendLine($"- Lower Band: ${indicators.BollingerLower:F2}");
                sb.AppendLine();

                sb.AppendLine("Volume Analysis:");
                sb.AppendLine($"- Average Volume (20-day): {indicators.AverageVolume_20:N0}");
                sb.AppendLine($"- Volume Change: {indicators.VolumeChangePercent:F2}%");
                sb.AppendLine();

                sb.AppendLine("Price Metrics:");
                sb.AppendLine($"- Day Change: {indicators.DayChangePercent:F2}%");
                sb.AppendLine($"- 52-Week High: ${indicators.Week52High:F2}");
                sb.AppendLine($"- 52-Week Low: ${indicators.Week52Low:F2}");
                sb.AppendLine($"- Price vs SMA 50: {indicators.PriceVsSMA50}");
                sb.AppendLine($"- Price vs SMA 200: {indicators.PriceVsSMA200}");
                sb.AppendLine();
            }

            sb.AppendLine("Please provide a comprehensive stock analysis based on the above data and the user's prompt.");

            return sb.ToString();
        }
    }
}
